# Generated by Django 4.2.2 on 2023-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default_image.jpg', upload_to='product_images/'),
        ),
    ]
